/**
 * Selling Partner API for FBA Small And Light
 * The Selling Partner API for FBA Small and Light lets you help sellers manage their listings in the Small and Light program. The program reduces the cost of fulfilling orders for small and lightweight FBA inventory. You can enroll or remove items from the program and check item eligibility and enrollment status. You can also preview the estimated program fees charged to a seller for items sold while enrolled in the program.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForFbaSmallAndLight);
  }
}(this, function(expect, SellingPartnerApiForFbaSmallAndLight) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FeePreview', function() {
    it('should create an instance of FeePreview', function() {
      // uncomment below and update the code to test FeePreview
      //var instane = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
      //expect(instance).to.be.a(SellingPartnerApiForFbaSmallAndLight.FeePreview);
    });

    it('should have the property asin (base name: "asin")', function() {
      // uncomment below and update the code to test the property asin
      //var instane = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
      //expect(instance).to.be();
    });

    it('should have the property feeBreakdown (base name: "feeBreakdown")', function() {
      // uncomment below and update the code to test the property feeBreakdown
      //var instane = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
      //expect(instance).to.be();
    });

    it('should have the property totalFees (base name: "totalFees")', function() {
      // uncomment below and update the code to test the property totalFees
      //var instane = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instane = new SellingPartnerApiForFbaSmallAndLight.FeePreview();
      //expect(instance).to.be();
    });

  });

}));
