/**
 * Selling Partner API for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForFulfillmentOutbound);
  }
}(this, function(expect, SellingPartnerApiForFulfillmentOutbound) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FulfillmentOrderItem', function() {
    it('should create an instance of FulfillmentOrderItem', function() {
      // uncomment below and update the code to test FulfillmentOrderItem
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be.a(SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem);
    });

    it('should have the property sellerSKU (base name: "SellerSKU")', function() {
      // uncomment below and update the code to test the property sellerSKU
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property sellerFulfillmentOrderItemId (base name: "SellerFulfillmentOrderItemId")', function() {
      // uncomment below and update the code to test the property sellerFulfillmentOrderItemId
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "Quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property giftMessage (base name: "GiftMessage")', function() {
      // uncomment below and update the code to test the property giftMessage
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property displayableComment (base name: "DisplayableComment")', function() {
      // uncomment below and update the code to test the property displayableComment
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property fulfillmentNetworkSKU (base name: "FulfillmentNetworkSKU")', function() {
      // uncomment below and update the code to test the property fulfillmentNetworkSKU
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property orderItemDisposition (base name: "OrderItemDisposition")', function() {
      // uncomment below and update the code to test the property orderItemDisposition
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property cancelledQuantity (base name: "CancelledQuantity")', function() {
      // uncomment below and update the code to test the property cancelledQuantity
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property unfulfillableQuantity (base name: "UnfulfillableQuantity")', function() {
      // uncomment below and update the code to test the property unfulfillableQuantity
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property estimatedShipDateTime (base name: "EstimatedShipDateTime")', function() {
      // uncomment below and update the code to test the property estimatedShipDateTime
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property estimatedArrivalDateTime (base name: "EstimatedArrivalDateTime")', function() {
      // uncomment below and update the code to test the property estimatedArrivalDateTime
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property perUnitPrice (base name: "PerUnitPrice")', function() {
      // uncomment below and update the code to test the property perUnitPrice
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property perUnitTax (base name: "PerUnitTax")', function() {
      // uncomment below and update the code to test the property perUnitTax
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

    it('should have the property perUnitDeclaredValue (base name: "PerUnitDeclaredValue")', function() {
      // uncomment below and update the code to test the property perUnitDeclaredValue
      //var instane = new SellingPartnerApiForFulfillmentOutbound.FulfillmentOrderItem();
      //expect(instance).to.be();
    });

  });

}));
