/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForFulfillmentInbound);
  }
}(this, function(expect, SellingPartnerApiForFulfillmentInbound) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InboundShipmentPlan', function() {
    it('should create an instance of InboundShipmentPlan', function() {
      // uncomment below and update the code to test InboundShipmentPlan
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be.a(SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan);
    });

    it('should have the property shipmentId (base name: "ShipmentId")', function() {
      // uncomment below and update the code to test the property shipmentId
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be();
    });

    it('should have the property destinationFulfillmentCenterId (base name: "DestinationFulfillmentCenterId")', function() {
      // uncomment below and update the code to test the property destinationFulfillmentCenterId
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be();
    });

    it('should have the property shipToAddress (base name: "ShipToAddress")', function() {
      // uncomment below and update the code to test the property shipToAddress
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be();
    });

    it('should have the property labelPrepType (base name: "LabelPrepType")', function() {
      // uncomment below and update the code to test the property labelPrepType
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "Items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be();
    });

    it('should have the property estimatedBoxContentsFee (base name: "EstimatedBoxContentsFee")', function() {
      // uncomment below and update the code to test the property estimatedBoxContentsFee
      //var instane = new SellingPartnerApiForFulfillmentInbound.InboundShipmentPlan();
      //expect(instance).to.be();
    });

  });

}));
