/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForPricing);
  }
}(this, function(expect, SellingPartnerApiForPricing) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForPricing.OfferDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OfferDetail', function() {
    it('should create an instance of OfferDetail', function() {
      // uncomment below and update the code to test OfferDetail
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be.a(SellingPartnerApiForPricing.OfferDetail);
    });

    it('should have the property myOffer (base name: "MyOffer")', function() {
      // uncomment below and update the code to test the property myOffer
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property subCondition (base name: "SubCondition")', function() {
      // uncomment below and update the code to test the property subCondition
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property sellerFeedbackRating (base name: "SellerFeedbackRating")', function() {
      // uncomment below and update the code to test the property sellerFeedbackRating
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property shippingTime (base name: "ShippingTime")', function() {
      // uncomment below and update the code to test the property shippingTime
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property listingPrice (base name: "ListingPrice")', function() {
      // uncomment below and update the code to test the property listingPrice
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property points (base name: "Points")', function() {
      // uncomment below and update the code to test the property points
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property shipping (base name: "Shipping")', function() {
      // uncomment below and update the code to test the property shipping
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property shipsFrom (base name: "ShipsFrom")', function() {
      // uncomment below and update the code to test the property shipsFrom
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property isFulfilledByAmazon (base name: "IsFulfilledByAmazon")', function() {
      // uncomment below and update the code to test the property isFulfilledByAmazon
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property isBuyBoxWinner (base name: "IsBuyBoxWinner")', function() {
      // uncomment below and update the code to test the property isBuyBoxWinner
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

    it('should have the property isFeaturedMerchant (base name: "IsFeaturedMerchant")', function() {
      // uncomment below and update the code to test the property isFeaturedMerchant
      //var instane = new SellingPartnerApiForPricing.OfferDetail();
      //expect(instance).to.be();
    });

  });

}));
