/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForMerchantFulfillment);
  }
}(this, function(expect, SellingPartnerApiForMerchantFulfillment) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PackageDimensions', function() {
    it('should create an instance of PackageDimensions', function() {
      // uncomment below and update the code to test PackageDimensions
      //var instane = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
      //expect(instance).to.be.a(SellingPartnerApiForMerchantFulfillment.PackageDimensions);
    });

    it('should have the property length (base name: "Length")', function() {
      // uncomment below and update the code to test the property length
      //var instane = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "Width")', function() {
      // uncomment below and update the code to test the property width
      //var instane = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "Height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "Unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instane = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
      //expect(instance).to.be();
    });

    it('should have the property predefinedPackageDimensions (base name: "PredefinedPackageDimensions")', function() {
      // uncomment below and update the code to test the property predefinedPackageDimensions
      //var instane = new SellingPartnerApiForMerchantFulfillment.PackageDimensions();
      //expect(instance).to.be();
    });

  });

}));
