/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForShipping);
  }
}(this, function(expect, SellingPartnerApiForShipping) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForShipping.Rate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Rate', function() {
    it('should create an instance of Rate', function() {
      // uncomment below and update the code to test Rate
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be.a(SellingPartnerApiForShipping.Rate);
    });

    it('should have the property rateId (base name: "rateId")', function() {
      // uncomment below and update the code to test the property rateId
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be();
    });

    it('should have the property totalCharge (base name: "totalCharge")', function() {
      // uncomment below and update the code to test the property totalCharge
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be();
    });

    it('should have the property billedWeight (base name: "billedWeight")', function() {
      // uncomment below and update the code to test the property billedWeight
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be();
    });

    it('should have the property expirationTime (base name: "expirationTime")', function() {
      // uncomment below and update the code to test the property expirationTime
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be();
    });

    it('should have the property serviceType (base name: "serviceType")', function() {
      // uncomment below and update the code to test the property serviceType
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be();
    });

    it('should have the property promise (base name: "promise")', function() {
      // uncomment below and update the code to test the property promise
      //var instane = new SellingPartnerApiForShipping.Rate();
      //expect(instance).to.be();
    });

  });

}));
