/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForFinances);
  }
}(this, function(expect, SellingPartnerApiForFinances) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForFinances.RemovalShipmentItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RemovalShipmentItem', function() {
    it('should create an instance of RemovalShipmentItem', function() {
      // uncomment below and update the code to test RemovalShipmentItem
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be.a(SellingPartnerApiForFinances.RemovalShipmentItem);
    });

    it('should have the property removalShipmentItemId (base name: "RemovalShipmentItemId")', function() {
      // uncomment below and update the code to test the property removalShipmentItemId
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property taxCollectionModel (base name: "TaxCollectionModel")', function() {
      // uncomment below and update the code to test the property taxCollectionModel
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property fulfillmentNetworkSKU (base name: "FulfillmentNetworkSKU")', function() {
      // uncomment below and update the code to test the property fulfillmentNetworkSKU
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "Quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property revenue (base name: "Revenue")', function() {
      // uncomment below and update the code to test the property revenue
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property feeAmount (base name: "FeeAmount")', function() {
      // uncomment below and update the code to test the property feeAmount
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property taxAmount (base name: "TaxAmount")', function() {
      // uncomment below and update the code to test the property taxAmount
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

    it('should have the property taxWithheld (base name: "TaxWithheld")', function() {
      // uncomment below and update the code to test the property taxWithheld
      //var instane = new SellingPartnerApiForFinances.RemovalShipmentItem();
      //expect(instance).to.be();
    });

  });

}));
