/**
 * Selling Partner API for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AdditionalLocationInfo.
* @enum {}
* @readonly
*/
export default class AdditionalLocationInfo {
        /**
         * value: "AS_INSTRUCTED"
         * @const
         */
        AS_INSTRUCTED = "AS_INSTRUCTED";

        /**
         * value: "CARPORT"
         * @const
         */
        CARPORT = "CARPORT";

        /**
         * value: "CUSTOMER_PICKUP"
         * @const
         */
        CUSTOMER_PICKUP = "CUSTOMER_PICKUP";

        /**
         * value: "DECK"
         * @const
         */
        DECK = "DECK";

        /**
         * value: "DOOR_PERSON"
         * @const
         */
        DOOR_PERSON = "DOOR_PERSON";

        /**
         * value: "FRONT_DESK"
         * @const
         */
        FRONT_DESK = "FRONT_DESK";

        /**
         * value: "FRONT_DOOR"
         * @const
         */
        FRONT_DOOR = "FRONT_DOOR";

        /**
         * value: "GARAGE"
         * @const
         */
        GARAGE = "GARAGE";

        /**
         * value: "GUARD"
         * @const
         */
        GUARD = "GUARD";

        /**
         * value: "MAIL_ROOM"
         * @const
         */
        MAIL_ROOM = "MAIL_ROOM";

        /**
         * value: "MAIL_SLOT"
         * @const
         */
        MAIL_SLOT = "MAIL_SLOT";

        /**
         * value: "MAILBOX"
         * @const
         */
        MAILBOX = "MAILBOX";

        /**
         * value: "MC_BOY"
         * @const
         */
        MC_BOY = "MC_BOY";

        /**
         * value: "MC_GIRL"
         * @const
         */
        MC_GIRL = "MC_GIRL";

        /**
         * value: "MC_MAN"
         * @const
         */
        MC_MAN = "MC_MAN";

        /**
         * value: "MC_WOMAN"
         * @const
         */
        MC_WOMAN = "MC_WOMAN";

        /**
         * value: "NEIGHBOR"
         * @const
         */
        NEIGHBOR = "NEIGHBOR";

        /**
         * value: "OFFICE"
         * @const
         */
        OFFICE = "OFFICE";

        /**
         * value: "OUTBUILDING"
         * @const
         */
        OUTBUILDING = "OUTBUILDING";

        /**
         * value: "PATIO"
         * @const
         */
        PATIO = "PATIO";

        /**
         * value: "PORCH"
         * @const
         */
        PORCH = "PORCH";

        /**
         * value: "REAR_DOOR"
         * @const
         */
        REAR_DOOR = "REAR_DOOR";

        /**
         * value: "RECEPTIONIST"
         * @const
         */
        RECEPTIONIST = "RECEPTIONIST";

        /**
         * value: "RECEIVER"
         * @const
         */
        RECEIVER = "RECEIVER";

        /**
         * value: "SECURE_LOCATION"
         * @const
         */
        SECURE_LOCATION = "SECURE_LOCATION";

        /**
         * value: "SIDE_DOOR"
         * @const
         */
        SIDE_DOOR = "SIDE_DOOR";


    /**
    * Returns a <code>AdditionalLocationInfo</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:client/models/AdditionalLocationInfo} The enum <code>AdditionalLocationInfo</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
