/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuidanceReasonList from './GuidanceReasonList';
import InboundGuidance from './InboundGuidance';

/**
* The ASINInboundGuidance model module.
* @module client/models/ASINInboundGuidance
* @version v0
*/
export default class ASINInboundGuidance {
    /**
    * Constructs a new <code>ASINInboundGuidance</code>.
    * Reasons why a given ASIN is not recommended for shipment to Amazon&#x27;s fulfillment network.
    * @alias module:client/models/ASINInboundGuidance
    * @class
    * @param ASIN {String} The Amazon Standard Identification Number (ASIN) of the item.
    * @param inboundGuidance {module:client/models/InboundGuidance} 
    */

    constructor(ASIN, inboundGuidance) {
        
        
        this['ASIN'] = ASIN;
        this['InboundGuidance'] = inboundGuidance;
        
    }

    /**
    * Constructs a <code>ASINInboundGuidance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ASINInboundGuidance} obj Optional instance to populate.
    * @return {module:client/models/ASINInboundGuidance} The populated <code>ASINInboundGuidance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ASINInboundGuidance();
                        
            
            if (data.hasOwnProperty('ASIN')) {
                obj['ASIN'] = ApiClient.convertToType(data['ASIN'], 'String');
            }
            if (data.hasOwnProperty('InboundGuidance')) {
                obj['InboundGuidance'] = InboundGuidance.constructFromObject(data['InboundGuidance']);
            }
            if (data.hasOwnProperty('GuidanceReasonList')) {
                obj['GuidanceReasonList'] = GuidanceReasonList.constructFromObject(data['GuidanceReasonList']);
            }
        }
        return obj;
    }

    /**
    * The Amazon Standard Identification Number (ASIN) of the item.
    * @member {String} ASIN
    */
    'ASIN' = undefined;
    /**
    * @member {module:client/models/InboundGuidance} InboundGuidance
    */
    'InboundGuidance' = undefined;
    /**
    * @member {module:client/models/GuidanceReasonList} GuidanceReasonList
    */
    'GuidanceReasonList' = undefined;




}
