/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AttributeSetList model module.
* @module client/models/AttributeSetList
* @version v0
*/
export default class AttributeSetList extends Array {
    /**
    * Constructs a new <code>AttributeSetList</code>.
    * A list of product attributes if they are applicable to the product that is returned.
    * @alias module:client/models/AttributeSetList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>AttributeSetList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/AttributeSetList} obj Optional instance to populate.
    * @return {module:client/models/AttributeSetList} The populated <code>AttributeSetList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributeSetList();
            ApiClient.constructFromObject(data, obj, 'Object');
            
            
        }
        return obj;
    }





}
