/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BarcodeInstruction.
* @enum {}
* @readonly
*/
export default class BarcodeInstruction {
        /**
         * value: "RequiresFNSKULabel"
         * @const
         */
        RequiresFNSKULabel = "RequiresFNSKULabel";

        /**
         * value: "CanUseOriginalBarcode"
         * @const
         */
        CanUseOriginalBarcode = "CanUseOriginalBarcode";

        /**
         * value: "MustProvideSellerSKU"
         * @const
         */
        MustProvideSellerSKU = "MustProvideSellerSKU";


    /**
    * Returns a <code>BarcodeInstruction</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:client/models/BarcodeInstruction} The enum <code>BarcodeInstruction</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
