/**
 * Selling Partner API for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';

/**
* The CODSettings model module.
* @module client/models/CODSettings
* @version v0
*/
export default class CODSettings {
    /**
    * Constructs a new <code>CODSettings</code>.
    * The COD (Cash On Delivery) charges that you associate with a COD fulfillment order.
    * @alias module:client/models/CODSettings
    * @class
    * @param isCODRequired {Boolean} Indicates whether this fulfillment order requires COD (Cash On Delivery) payment.
    */

    constructor(isCODRequired) {
        
        
        this['IsCODRequired'] = isCODRequired;
        
    }

    /**
    * Constructs a <code>CODSettings</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/CODSettings} obj Optional instance to populate.
    * @return {module:client/models/CODSettings} The populated <code>CODSettings</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CODSettings();
                        
            
            if (data.hasOwnProperty('IsCODRequired')) {
                obj['IsCODRequired'] = ApiClient.convertToType(data['IsCODRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('CODCharge')) {
                obj['CODCharge'] = Currency.constructFromObject(data['CODCharge']);
            }
            if (data.hasOwnProperty('CODChargeTax')) {
                obj['CODChargeTax'] = Currency.constructFromObject(data['CODChargeTax']);
            }
            if (data.hasOwnProperty('ShippingCharge')) {
                obj['ShippingCharge'] = Currency.constructFromObject(data['ShippingCharge']);
            }
            if (data.hasOwnProperty('ShippingChargeTax')) {
                obj['ShippingChargeTax'] = Currency.constructFromObject(data['ShippingChargeTax']);
            }
        }
        return obj;
    }

    /**
    * Indicates whether this fulfillment order requires COD (Cash On Delivery) payment.
    * @member {Boolean} IsCODRequired
    */
    'IsCODRequired' = undefined;
    /**
    * @member {module:client/models/Currency} CODCharge
    */
    'CODCharge' = undefined;
    /**
    * @member {module:client/models/Currency} CODChargeTax
    */
    'CODChargeTax' = undefined;
    /**
    * @member {module:client/models/Currency} ShippingCharge
    */
    'ShippingCharge' = undefined;
    /**
    * @member {module:client/models/Currency} ShippingChargeTax
    */
    'ShippingChargeTax' = undefined;




}
