/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompetitivePriceType from './CompetitivePriceType';

/**
* The CompetitivePriceList model module.
* @module client/models/CompetitivePriceList
* @version v0
*/
export default class CompetitivePriceList extends Array {
    /**
    * Constructs a new <code>CompetitivePriceList</code>.
    * A list of competitive pricing information.
    * @alias module:client/models/CompetitivePriceList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>CompetitivePriceList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/CompetitivePriceList} obj Optional instance to populate.
    * @return {module:client/models/CompetitivePriceList} The populated <code>CompetitivePriceList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitivePriceList();
            ApiClient.constructFromObject(data, obj, 'CompetitivePriceType');
            
            
        }
        return obj;
    }





}
