/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Condition.
* @enum {}
* @readonly
*/
export default class Condition {
        /**
         * value: "NewItem"
         * @const
         */
        NewItem = "NewItem";

        /**
         * value: "NewWithWarranty"
         * @const
         */
        NewWithWarranty = "NewWithWarranty";

        /**
         * value: "NewOEM"
         * @const
         */
        NewOEM = "NewOEM";

        /**
         * value: "NewOpenBox"
         * @const
         */
        NewOpenBox = "NewOpenBox";

        /**
         * value: "UsedLikeNew"
         * @const
         */
        UsedLikeNew = "UsedLikeNew";

        /**
         * value: "UsedVeryGood"
         * @const
         */
        UsedVeryGood = "UsedVeryGood";

        /**
         * value: "UsedGood"
         * @const
         */
        UsedGood = "UsedGood";

        /**
         * value: "UsedAcceptable"
         * @const
         */
        UsedAcceptable = "UsedAcceptable";

        /**
         * value: "UsedPoor"
         * @const
         */
        UsedPoor = "UsedPoor";

        /**
         * value: "UsedRefurbished"
         * @const
         */
        UsedRefurbished = "UsedRefurbished";

        /**
         * value: "CollectibleLikeNew"
         * @const
         */
        CollectibleLikeNew = "CollectibleLikeNew";

        /**
         * value: "CollectibleVeryGood"
         * @const
         */
        CollectibleVeryGood = "CollectibleVeryGood";

        /**
         * value: "CollectibleGood"
         * @const
         */
        CollectibleGood = "CollectibleGood";

        /**
         * value: "CollectibleAcceptable"
         * @const
         */
        CollectibleAcceptable = "CollectibleAcceptable";

        /**
         * value: "CollectiblePoor"
         * @const
         */
        CollectiblePoor = "CollectiblePoor";

        /**
         * value: "RefurbishedWithWarranty"
         * @const
         */
        RefurbishedWithWarranty = "RefurbishedWithWarranty";

        /**
         * value: "Refurbished"
         * @const
         */
        Refurbished = "Refurbished";

        /**
         * value: "Club"
         * @const
         */
        Club = "Club";


    /**
    * Returns a <code>Condition</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:client/models/Condition} The enum <code>Condition</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
