/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Container from './Container';

/**
* The ContainerList model module.
* @module client/models/ContainerList
* @version v1
*/
export default class ContainerList extends Array {
    /**
    * Constructs a new <code>ContainerList</code>.
    * A list of container.
    * @alias module:client/models/ContainerList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>ContainerList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ContainerList} obj Optional instance to populate.
    * @return {module:client/models/ContainerList} The populated <code>ContainerList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerList();
            ApiClient.constructFromObject(data, obj, 'Container');
            
            
        }
        return obj;
    }





}
