/**
 * Selling Partner API for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvalidReturnItemList from './InvalidReturnItemList';
import ReturnAuthorizationList from './ReturnAuthorizationList';
import ReturnItemList from './ReturnItemList';

/**
* The CreateFulfillmentReturnResult model module.
* @module client/models/CreateFulfillmentReturnResult
* @version v0
*/
export default class CreateFulfillmentReturnResult {
    /**
    * Constructs a new <code>CreateFulfillmentReturnResult</code>.
    * @alias module:client/models/CreateFulfillmentReturnResult
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateFulfillmentReturnResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/CreateFulfillmentReturnResult} obj Optional instance to populate.
    * @return {module:client/models/CreateFulfillmentReturnResult} The populated <code>CreateFulfillmentReturnResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFulfillmentReturnResult();
                        
            
            if (data.hasOwnProperty('ReturnItemList')) {
                obj['ReturnItemList'] = ReturnItemList.constructFromObject(data['ReturnItemList']);
            }
            if (data.hasOwnProperty('InvalidReturnItemList')) {
                obj['InvalidReturnItemList'] = InvalidReturnItemList.constructFromObject(data['InvalidReturnItemList']);
            }
            if (data.hasOwnProperty('ReturnAuthorizationList')) {
                obj['ReturnAuthorizationList'] = ReturnAuthorizationList.constructFromObject(data['ReturnAuthorizationList']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/ReturnItemList} ReturnItemList
    */
    'ReturnItemList' = undefined;
    /**
    * @member {module:client/models/InvalidReturnItemList} InvalidReturnItemList
    */
    'InvalidReturnItemList' = undefined;
    /**
    * @member {module:client/models/ReturnAuthorizationList} ReturnAuthorizationList
    */
    'ReturnAuthorizationList' = undefined;




}
