/**
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2020-09-04
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportOptions from './ReportOptions';

/**
* The CreateReportScheduleSpecification model module.
* @module client/models/CreateReportScheduleSpecification
* @version 2020-09-04
*/
export default class CreateReportScheduleSpecification {
    /**
    * Constructs a new <code>CreateReportScheduleSpecification</code>.
    * @alias module:client/models/CreateReportScheduleSpecification
    * @class
    * @param reportType {String} The report type.
    * @param marketplaceIds {Array.<String>} A list of marketplace identifiers for the report schedule.
    * @param period {module:client/models/CreateReportScheduleSpecification.PeriodEnum} One of a set of predefined ISO 8601 periods that specifies how often a report should be created.
    */

    constructor(reportType, marketplaceIds, period) {
        
        
        this['reportType'] = reportType;
        this['marketplaceIds'] = marketplaceIds;
        this['period'] = period;
        
    }

    /**
    * Constructs a <code>CreateReportScheduleSpecification</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/CreateReportScheduleSpecification} obj Optional instance to populate.
    * @return {module:client/models/CreateReportScheduleSpecification} The populated <code>CreateReportScheduleSpecification</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateReportScheduleSpecification();
                        
            
            if (data.hasOwnProperty('reportType')) {
                obj['reportType'] = ApiClient.convertToType(data['reportType'], 'String');
            }
            if (data.hasOwnProperty('marketplaceIds')) {
                obj['marketplaceIds'] = ApiClient.convertToType(data['marketplaceIds'], ['String']);
            }
            if (data.hasOwnProperty('reportOptions')) {
                obj['reportOptions'] = ReportOptions.constructFromObject(data['reportOptions']);
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'String');
            }
            if (data.hasOwnProperty('nextReportCreationTime')) {
                obj['nextReportCreationTime'] = ApiClient.convertToType(data['nextReportCreationTime'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The report type.
    * @member {String} reportType
    */
    'reportType' = undefined;
    /**
    * A list of marketplace identifiers for the report schedule.
    * @member {Array.<String>} marketplaceIds
    */
    'marketplaceIds' = undefined;
    /**
    * @member {module:client/models/ReportOptions} reportOptions
    */
    'reportOptions' = undefined;
    /**
    * One of a set of predefined ISO 8601 periods that specifies how often a report should be created.
    * @member {module:client/models/CreateReportScheduleSpecification.PeriodEnum} period
    */
    'period' = undefined;
    /**
    * The date and time when the schedule will create its next report, in ISO 8601 date time format.
    * @member {Date} nextReportCreationTime
    */
    'nextReportCreationTime' = undefined;



    /**
    * Allowed values for the <code>period</code> property.
    * @enum {String}
    * @readonly
    */
    static PeriodEnum = {
        /**
         * value: "PT5M"
         * @const
         */
        "PT5M": "PT5M",
        /**
         * value: "PT15M"
         * @const
         */
        "PT15M": "PT15M",
        /**
         * value: "PT30M"
         * @const
         */
        "PT30M": "PT30M",
        /**
         * value: "PT1H"
         * @const
         */
        "PT1H": "PT1H",
        /**
         * value: "PT2H"
         * @const
         */
        "PT2H": "PT2H",
        /**
         * value: "PT4H"
         * @const
         */
        "PT4H": "PT4H",
        /**
         * value: "PT8H"
         * @const
         */
        "PT8H": "PT8H",
        /**
         * value: "PT12H"
         * @const
         */
        "PT12H": "PT12H",
        /**
         * value: "P1D"
         * @const
         */
        "P1D": "P1D",
        /**
         * value: "P2D"
         * @const
         */
        "P2D": "P2D",
        /**
         * value: "P3D"
         * @const
         */
        "P3D": "P3D",
        /**
         * value: "PT84H"
         * @const
         */
        "PT84H": "PT84H",
        /**
         * value: "P7D"
         * @const
         */
        "P7D": "P7D",
        /**
         * value: "P14D"
         * @const
         */
        "P14D": "P14D",
        /**
         * value: "P15D"
         * @const
         */
        "P15D": "P15D",
        /**
         * value: "P18D"
         * @const
         */
        "P18D": "P18D",
        /**
         * value: "P30D"
         * @const
         */
        "P30D": "P30D",
        /**
         * value: "P1M"
         * @const
         */
        "P1M": "P1M"    };

}
