/**
 * Selling Partner API for Sales
 * The Selling Partner API for Sales provides APIs related to sales performance.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Decimal model module.
* @module client/models/Decimal
* @version v1
*/
export default class Decimal {
    /**
    * Constructs a new <code>Decimal</code>.
    * A decimal number with no loss of precision. Useful when precision loss is unnaceptable, as with currencies. Follows RFC7159 for number representation.
    * @alias module:client/models/Decimal
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Decimal</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/Decimal} obj Optional instance to populate.
    * @return {module:client/models/Decimal} The populated <code>Decimal</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Decimal();
                        
            
        }
        return obj;
    }





}
