/**
 * Selling Partner API for Product Fees
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncludedFeeDetailList from './IncludedFeeDetailList';
import MoneyType from './MoneyType';

/**
* The FeeDetail model module.
* @module client/models/FeeDetail
* @version v0
*/
export default class FeeDetail {
    /**
    * Constructs a new <code>FeeDetail</code>.
    * The type of fee, fee amount, and other details.
    * @alias module:client/models/FeeDetail
    * @class
    * @param feeType {String} The type of fee charged to a seller.
    * @param feeAmount {module:client/models/MoneyType} 
    * @param finalFee {module:client/models/MoneyType} 
    */

    constructor(feeType, feeAmount, finalFee) {
        
        
        this['FeeType'] = feeType;
        this['FeeAmount'] = feeAmount;
        this['FinalFee'] = finalFee;
        
    }

    /**
    * Constructs a <code>FeeDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/FeeDetail} obj Optional instance to populate.
    * @return {module:client/models/FeeDetail} The populated <code>FeeDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeeDetail();
                        
            
            if (data.hasOwnProperty('FeeType')) {
                obj['FeeType'] = ApiClient.convertToType(data['FeeType'], 'String');
            }
            if (data.hasOwnProperty('FeeAmount')) {
                obj['FeeAmount'] = MoneyType.constructFromObject(data['FeeAmount']);
            }
            if (data.hasOwnProperty('FeePromotion')) {
                obj['FeePromotion'] = MoneyType.constructFromObject(data['FeePromotion']);
            }
            if (data.hasOwnProperty('TaxAmount')) {
                obj['TaxAmount'] = MoneyType.constructFromObject(data['TaxAmount']);
            }
            if (data.hasOwnProperty('FinalFee')) {
                obj['FinalFee'] = MoneyType.constructFromObject(data['FinalFee']);
            }
            if (data.hasOwnProperty('IncludedFeeDetailList')) {
                obj['IncludedFeeDetailList'] = IncludedFeeDetailList.constructFromObject(data['IncludedFeeDetailList']);
            }
        }
        return obj;
    }

    /**
    * The type of fee charged to a seller.
    * @member {String} FeeType
    */
    'FeeType' = undefined;
    /**
    * @member {module:client/models/MoneyType} FeeAmount
    */
    'FeeAmount' = undefined;
    /**
    * @member {module:client/models/MoneyType} FeePromotion
    */
    'FeePromotion' = undefined;
    /**
    * @member {module:client/models/MoneyType} TaxAmount
    */
    'TaxAmount' = undefined;
    /**
    * @member {module:client/models/MoneyType} FinalFee
    */
    'FinalFee' = undefined;
    /**
    * @member {module:client/models/IncludedFeeDetailList} IncludedFeeDetailList
    */
    'IncludedFeeDetailList' = undefined;




}
