/**
 * Selling Partner API for FBA Small And Light
 * The Selling Partner API for FBA Small and Light lets you help sellers manage their listings in the Small and Light program. The program reduces the cost of fulfilling orders for small and lightweight FBA inventory. You can enroll or remove items from the program and check item eligibility and enrollment status. You can also preview the estimated program fees charged to a seller for items sold while enrolled in the program.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MoneyType from './MoneyType';

/**
* The FeeLineItem model module.
* @module client/models/FeeLineItem
* @version v1
*/
export default class FeeLineItem {
    /**
    * Constructs a new <code>FeeLineItem</code>.
    * Fee details for a specific fee.
    * @alias module:client/models/FeeLineItem
    * @class
    * @param feeType {module:client/models/FeeLineItem.FeeTypeEnum} The type of fee charged to the seller.
    * @param feeCharge {module:client/models/MoneyType} 
    */

    constructor(feeType, feeCharge) {
        
        
        this['feeType'] = feeType;
        this['feeCharge'] = feeCharge;
        
    }

    /**
    * Constructs a <code>FeeLineItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/FeeLineItem} obj Optional instance to populate.
    * @return {module:client/models/FeeLineItem} The populated <code>FeeLineItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeeLineItem();
                        
            
            if (data.hasOwnProperty('feeType')) {
                obj['feeType'] = ApiClient.convertToType(data['feeType'], 'String');
            }
            if (data.hasOwnProperty('feeCharge')) {
                obj['feeCharge'] = MoneyType.constructFromObject(data['feeCharge']);
            }
        }
        return obj;
    }

    /**
    * The type of fee charged to the seller.
    * @member {module:client/models/FeeLineItem.FeeTypeEnum} feeType
    */
    'feeType' = undefined;
    /**
    * @member {module:client/models/MoneyType} feeCharge
    */
    'feeCharge' = undefined;



    /**
    * Allowed values for the <code>feeType</code> property.
    * @enum {String}
    * @readonly
    */
    static FeeTypeEnum = {
        /**
         * value: "FBAWeightBasedFee"
         * @const
         */
        "FBAWeightBasedFee": "FBAWeightBasedFee",
        /**
         * value: "FBAPerOrderFulfillmentFee"
         * @const
         */
        "FBAPerOrderFulfillmentFee": "FBAPerOrderFulfillmentFee",
        /**
         * value: "FBAPerUnitFulfillmentFee"
         * @const
         */
        "FBAPerUnitFulfillmentFee": "FBAPerUnitFulfillmentFee",
        /**
         * value: "Commission"
         * @const
         */
        "Commission": "Commission"    };

}
