/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileType from './FileType';

/**
* The FileContents model module.
* @module client/models/FileContents
* @version v0
*/
export default class FileContents {
    /**
    * Constructs a new <code>FileContents</code>.
    * The document data and checksum.
    * @alias module:client/models/FileContents
    * @class
    * @param contents {String} Data for printing labels, in the form of a Base64-encoded, GZip-compressed string.
    * @param fileType {module:client/models/FileType} 
    * @param checksum {String} An MD5 hash to validate the PDF document data, in the form of a Base64-encoded string.
    */

    constructor(contents, fileType, checksum) {
        
        
        this['Contents'] = contents;
        this['FileType'] = fileType;
        this['Checksum'] = checksum;
        
    }

    /**
    * Constructs a <code>FileContents</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/FileContents} obj Optional instance to populate.
    * @return {module:client/models/FileContents} The populated <code>FileContents</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileContents();
                        
            
            if (data.hasOwnProperty('Contents')) {
                obj['Contents'] = ApiClient.convertToType(data['Contents'], 'String');
            }
            if (data.hasOwnProperty('FileType')) {
                obj['FileType'] = FileType.constructFromObject(data['FileType']);
            }
            if (data.hasOwnProperty('Checksum')) {
                obj['Checksum'] = ApiClient.convertToType(data['Checksum'], 'String');
            }
        }
        return obj;
    }

    /**
    * Data for printing labels, in the form of a Base64-encoded, GZip-compressed string.
    * @member {String} Contents
    */
    'Contents' = undefined;
    /**
    * @member {module:client/models/FileType} FileType
    */
    'FileType' = undefined;
    /**
    * An MD5 hash to validate the PDF document data, in the form of a Base64-encoded string.
    * @member {String} Checksum
    */
    'Checksum' = undefined;




}
