/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorList from './ErrorList';
import GetAdditionalSellerInputsResult from './GetAdditionalSellerInputsResult';

/**
* The GetAdditionalSellerInputsResponse model module.
* @module client/models/GetAdditionalSellerInputsResponse
* @version v0
*/
export default class GetAdditionalSellerInputsResponse {
    /**
    * Constructs a new <code>GetAdditionalSellerInputsResponse</code>.
    * Response schema.
    * @alias module:client/models/GetAdditionalSellerInputsResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetAdditionalSellerInputsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetAdditionalSellerInputsResponse} obj Optional instance to populate.
    * @return {module:client/models/GetAdditionalSellerInputsResponse} The populated <code>GetAdditionalSellerInputsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAdditionalSellerInputsResponse();
                        
            
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = GetAdditionalSellerInputsResult.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ErrorList.constructFromObject(data['errors']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/GetAdditionalSellerInputsResult} payload
    */
    'payload' = undefined;
    /**
    * @member {module:client/models/ErrorList} errors
    */
    'errors' = undefined;




}
