/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RejectedShippingServiceList from './RejectedShippingServiceList';
import ShippingServiceList from './ShippingServiceList';
import TemporarilyUnavailableCarrierList from './TemporarilyUnavailableCarrierList';
import TermsAndConditionsNotAcceptedCarrierList from './TermsAndConditionsNotAcceptedCarrierList';

/**
* The GetEligibleShipmentServicesResult model module.
* @module client/models/GetEligibleShipmentServicesResult
* @version v0
*/
export default class GetEligibleShipmentServicesResult {
    /**
    * Constructs a new <code>GetEligibleShipmentServicesResult</code>.
    * The payload for the getEligibleShipmentServices operation.
    * @alias module:client/models/GetEligibleShipmentServicesResult
    * @class
    * @param shippingServiceList {module:client/models/ShippingServiceList} 
    */

    constructor(shippingServiceList) {
        
        
        this['ShippingServiceList'] = shippingServiceList;
        
    }

    /**
    * Constructs a <code>GetEligibleShipmentServicesResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetEligibleShipmentServicesResult} obj Optional instance to populate.
    * @return {module:client/models/GetEligibleShipmentServicesResult} The populated <code>GetEligibleShipmentServicesResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetEligibleShipmentServicesResult();
                        
            
            if (data.hasOwnProperty('ShippingServiceList')) {
                obj['ShippingServiceList'] = ShippingServiceList.constructFromObject(data['ShippingServiceList']);
            }
            if (data.hasOwnProperty('RejectedShippingServiceList')) {
                obj['RejectedShippingServiceList'] = RejectedShippingServiceList.constructFromObject(data['RejectedShippingServiceList']);
            }
            if (data.hasOwnProperty('TemporarilyUnavailableCarrierList')) {
                obj['TemporarilyUnavailableCarrierList'] = TemporarilyUnavailableCarrierList.constructFromObject(data['TemporarilyUnavailableCarrierList']);
            }
            if (data.hasOwnProperty('TermsAndConditionsNotAcceptedCarrierList')) {
                obj['TermsAndConditionsNotAcceptedCarrierList'] = TermsAndConditionsNotAcceptedCarrierList.constructFromObject(data['TermsAndConditionsNotAcceptedCarrierList']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/ShippingServiceList} ShippingServiceList
    */
    'ShippingServiceList' = undefined;
    /**
    * @member {module:client/models/RejectedShippingServiceList} RejectedShippingServiceList
    */
    'RejectedShippingServiceList' = undefined;
    /**
    * @member {module:client/models/TemporarilyUnavailableCarrierList} TemporarilyUnavailableCarrierList
    */
    'TemporarilyUnavailableCarrierList' = undefined;
    /**
    * @member {module:client/models/TermsAndConditionsNotAcceptedCarrierList} TermsAndConditionsNotAcceptedCarrierList
    */
    'TermsAndConditionsNotAcceptedCarrierList' = undefined;




}
