/**
 * Selling Partner API for Feeds
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * OpenAPI spec version: 2020-09-04
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorList from './ErrorList';
import Feed from './Feed';

/**
* The GetFeedResponse model module.
* @module client/models/GetFeedResponse
* @version 2020-09-04
*/
export default class GetFeedResponse {
    /**
    * Constructs a new <code>GetFeedResponse</code>.
    * Response schema.
    * @alias module:client/models/GetFeedResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetFeedResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetFeedResponse} obj Optional instance to populate.
    * @return {module:client/models/GetFeedResponse} The populated <code>GetFeedResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFeedResponse();
                        
            
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = Feed.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ErrorList.constructFromObject(data['errors']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/Feed} payload
    */
    'payload' = undefined;
    /**
    * @member {module:client/models/ErrorList} errors
    */
    'errors' = undefined;




}
