/**
 * Selling Partner API for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Quantity from './Quantity';

/**
* The GetFulfillmentPreviewItem model module.
* @module client/models/GetFulfillmentPreviewItem
* @version v0
*/
export default class GetFulfillmentPreviewItem {
    /**
    * Constructs a new <code>GetFulfillmentPreviewItem</code>.
    * Item information for a fulfillment order preview.
    * @alias module:client/models/GetFulfillmentPreviewItem
    * @class
    * @param sellerSKU {String} The seller SKU of the item.
    * @param quantity {module:client/models/Quantity} 
    * @param sellerFulfillmentOrderItemId {String} A fulfillment order item identifier that the seller creates to track items in the fulfillment preview.
    */

    constructor(sellerSKU, quantity, sellerFulfillmentOrderItemId) {
        
        
        this['SellerSKU'] = sellerSKU;
        this['Quantity'] = quantity;
        this['SellerFulfillmentOrderItemId'] = sellerFulfillmentOrderItemId;
        
    }

    /**
    * Constructs a <code>GetFulfillmentPreviewItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetFulfillmentPreviewItem} obj Optional instance to populate.
    * @return {module:client/models/GetFulfillmentPreviewItem} The populated <code>GetFulfillmentPreviewItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFulfillmentPreviewItem();
                        
            
            if (data.hasOwnProperty('SellerSKU')) {
                obj['SellerSKU'] = ApiClient.convertToType(data['SellerSKU'], 'String');
            }
            if (data.hasOwnProperty('Quantity')) {
                obj['Quantity'] = Quantity.constructFromObject(data['Quantity']);
            }
            if (data.hasOwnProperty('SellerFulfillmentOrderItemId')) {
                obj['SellerFulfillmentOrderItemId'] = ApiClient.convertToType(data['SellerFulfillmentOrderItemId'], 'String');
            }
        }
        return obj;
    }

    /**
    * The seller SKU of the item.
    * @member {String} SellerSKU
    */
    'SellerSKU' = undefined;
    /**
    * @member {module:client/models/Quantity} Quantity
    */
    'Quantity' = undefined;
    /**
    * A fulfillment order item identifier that the seller creates to track items in the fulfillment preview.
    * @member {String} SellerFulfillmentOrderItemId
    */
    'SellerFulfillmentOrderItemId' = undefined;




}
