/**
 * Selling Partner API for FBA Inventory
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Granularity from './Granularity';
import InventorySummaries from './InventorySummaries';

/**
* The GetInventorySummariesResult model module.
* @module client/models/GetInventorySummariesResult
* @version v1
*/
export default class GetInventorySummariesResult {
    /**
    * Constructs a new <code>GetInventorySummariesResult</code>.
    * The payload schema for the getInventorySummaries operation.
    * @alias module:client/models/GetInventorySummariesResult
    * @class
    * @param granularity {module:client/models/Granularity} 
    * @param inventorySummaries {module:client/models/InventorySummaries} 
    */

    constructor(granularity, inventorySummaries) {
        
        
        this['granularity'] = granularity;
        this['inventorySummaries'] = inventorySummaries;
        
    }

    /**
    * Constructs a <code>GetInventorySummariesResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetInventorySummariesResult} obj Optional instance to populate.
    * @return {module:client/models/GetInventorySummariesResult} The populated <code>GetInventorySummariesResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetInventorySummariesResult();
                        
            
            if (data.hasOwnProperty('granularity')) {
                obj['granularity'] = Granularity.constructFromObject(data['granularity']);
            }
            if (data.hasOwnProperty('inventorySummaries')) {
                obj['inventorySummaries'] = InventorySummaries.constructFromObject(data['inventorySummaries']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/Granularity} granularity
    */
    'granularity' = undefined;
    /**
    * @member {module:client/models/InventorySummaries} inventorySummaries
    */
    'inventorySummaries' = undefined;




}
