/**
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorList from './ErrorList';
import OrderBuyerInfo from './OrderBuyerInfo';

/**
* The GetOrderBuyerInfoResponse model module.
* @module client/models/GetOrderBuyerInfoResponse
* @version v0
*/
export default class GetOrderBuyerInfoResponse {
    /**
    * Constructs a new <code>GetOrderBuyerInfoResponse</code>.
    * The response schema for the getOrderBuyerInfo operation.
    * @alias module:client/models/GetOrderBuyerInfoResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetOrderBuyerInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetOrderBuyerInfoResponse} obj Optional instance to populate.
    * @return {module:client/models/GetOrderBuyerInfoResponse} The populated <code>GetOrderBuyerInfoResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetOrderBuyerInfoResponse();
                        
            
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = OrderBuyerInfo.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ErrorList.constructFromObject(data['errors']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/OrderBuyerInfo} payload
    */
    'payload' = undefined;
    /**
    * @member {module:client/models/ErrorList} errors
    */
    'errors' = undefined;




}
