/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorList from './ErrorList';
import PriceList from './PriceList';

/**
* The GetPricingResponse model module.
* @module client/models/GetPricingResponse
* @version v0
*/
export default class GetPricingResponse {
    /**
    * Constructs a new <code>GetPricingResponse</code>.
    * The response schema for the getPricing and getCompetitivePricing operations.
    * @alias module:client/models/GetPricingResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetPricingResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetPricingResponse} obj Optional instance to populate.
    * @return {module:client/models/GetPricingResponse} The populated <code>GetPricingResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPricingResponse();
                        
            
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = PriceList.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ErrorList.constructFromObject(data['errors']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/PriceList} payload
    */
    'payload' = undefined;
    /**
    * @member {module:client/models/ErrorList} errors
    */
    'errors' = undefined;




}
