/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorList from './ErrorList';
import TrackingInformation from './TrackingInformation';

/**
* The GetTrackingInformationResponse model module.
* @module client/models/GetTrackingInformationResponse
* @version v1
*/
export default class GetTrackingInformationResponse {
    /**
    * Constructs a new <code>GetTrackingInformationResponse</code>.
    * The response schema for the getTrackingInformation operation.
    * @alias module:client/models/GetTrackingInformationResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GetTrackingInformationResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/GetTrackingInformationResponse} obj Optional instance to populate.
    * @return {module:client/models/GetTrackingInformationResponse} The populated <code>GetTrackingInformationResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTrackingInformationResponse();
                        
            
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = TrackingInformation.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ErrorList.constructFromObject(data['errors']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/TrackingInformation} payload
    */
    'payload' = undefined;
    /**
    * @member {module:client/models/ErrorList} errors
    */
    'errors' = undefined;




}
