/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Condition from './Condition';
import PrepDetailsList from './PrepDetailsList';
import Quantity from './Quantity';

/**
* The InboundShipmentPlanRequestItem model module.
* @module client/models/InboundShipmentPlanRequestItem
* @version v0
*/
export default class InboundShipmentPlanRequestItem {
    /**
    * Constructs a new <code>InboundShipmentPlanRequestItem</code>.
    * Item information for creating an inbound shipment plan. Submitted with a call to the createInboundShipmentPlan operation.
    * @alias module:client/models/InboundShipmentPlanRequestItem
    * @class
    * @param sellerSKU {String} The seller SKU of the item.
    * @param ASIN {String} The Amazon Standard Identification Number (ASIN) of the item.
    * @param condition {module:client/models/Condition} 
    * @param quantity {module:client/models/Quantity} 
    */

    constructor(sellerSKU, ASIN, condition, quantity) {
        
        
        this['SellerSKU'] = sellerSKU;
        this['ASIN'] = ASIN;
        this['Condition'] = condition;
        this['Quantity'] = quantity;
        
    }

    /**
    * Constructs a <code>InboundShipmentPlanRequestItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/InboundShipmentPlanRequestItem} obj Optional instance to populate.
    * @return {module:client/models/InboundShipmentPlanRequestItem} The populated <code>InboundShipmentPlanRequestItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InboundShipmentPlanRequestItem();
                        
            
            if (data.hasOwnProperty('SellerSKU')) {
                obj['SellerSKU'] = ApiClient.convertToType(data['SellerSKU'], 'String');
            }
            if (data.hasOwnProperty('ASIN')) {
                obj['ASIN'] = ApiClient.convertToType(data['ASIN'], 'String');
            }
            if (data.hasOwnProperty('Condition')) {
                obj['Condition'] = Condition.constructFromObject(data['Condition']);
            }
            if (data.hasOwnProperty('Quantity')) {
                obj['Quantity'] = Quantity.constructFromObject(data['Quantity']);
            }
            if (data.hasOwnProperty('QuantityInCase')) {
                obj['QuantityInCase'] = Quantity.constructFromObject(data['QuantityInCase']);
            }
            if (data.hasOwnProperty('PrepDetailsList')) {
                obj['PrepDetailsList'] = PrepDetailsList.constructFromObject(data['PrepDetailsList']);
            }
        }
        return obj;
    }

    /**
    * The seller SKU of the item.
    * @member {String} SellerSKU
    */
    'SellerSKU' = undefined;
    /**
    * The Amazon Standard Identification Number (ASIN) of the item.
    * @member {String} ASIN
    */
    'ASIN' = undefined;
    /**
    * @member {module:client/models/Condition} Condition
    */
    'Condition' = undefined;
    /**
    * @member {module:client/models/Quantity} Quantity
    */
    'Quantity' = undefined;
    /**
    * @member {module:client/models/Quantity} QuantityInCase
    */
    'QuantityInCase' = undefined;
    /**
    * @member {module:client/models/PrepDetailsList} PrepDetailsList
    */
    'PrepDetailsList' = undefined;




}
