/**
 * Selling Partner API for Product Fees
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncludedFeeDetail from './IncludedFeeDetail';

/**
* The IncludedFeeDetailList model module.
* @module client/models/IncludedFeeDetailList
* @version v0
*/
export default class IncludedFeeDetailList extends Array {
    /**
    * Constructs a new <code>IncludedFeeDetailList</code>.
    * A list of other fees that contribute to a given fee.
    * @alias module:client/models/IncludedFeeDetailList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>IncludedFeeDetailList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/IncludedFeeDetailList} obj Optional instance to populate.
    * @return {module:client/models/IncludedFeeDetailList} The populated <code>IncludedFeeDetailList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IncludedFeeDetailList();
            ApiClient.constructFromObject(data, obj, 'IncludedFeeDetail');
            
            
        }
        return obj;
    }





}
