/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvalidSKU from './InvalidSKU';

/**
* The InvalidSKUList model module.
* @module client/models/InvalidSKUList
* @version v0
*/
export default class InvalidSKUList extends Array {
    /**
    * Constructs a new <code>InvalidSKUList</code>.
    * A list of invalid SKU values and the reason they are invalid.
    * @alias module:client/models/InvalidSKUList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>InvalidSKUList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/InvalidSKUList} obj Optional instance to populate.
    * @return {module:client/models/InvalidSKUList} The populated <code>InvalidSKUList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvalidSKUList();
            ApiClient.constructFromObject(data, obj, 'InvalidSKU');
            
            
        }
        return obj;
    }





}
