/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemDeliveryPromise from './ItemDeliveryPromise';

/**
* The ItemDelivery model module.
* @module client/models/ItemDelivery
* @version v1
*/
export default class ItemDelivery {
    /**
    * Constructs a new <code>ItemDelivery</code>.
    * Delivery information for the item.
    * @alias module:client/models/ItemDelivery
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ItemDelivery</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ItemDelivery} obj Optional instance to populate.
    * @return {module:client/models/ItemDelivery} The populated <code>ItemDelivery</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ItemDelivery();
                        
            
            if (data.hasOwnProperty('estimatedDeliveryDate')) {
                obj['estimatedDeliveryDate'] = ApiClient.convertToType(data['estimatedDeliveryDate'], 'Date');
            }
            if (data.hasOwnProperty('itemDeliveryPromise')) {
                obj['itemDeliveryPromise'] = ItemDeliveryPromise.constructFromObject(data['itemDeliveryPromise']);
            }
        }
        return obj;
    }

    /**
    * The date and time of the latest Estimated Delivery Date (EDD) of all the items with an EDD. In ISO 8601 format.
    * @member {Date} estimatedDeliveryDate
    */
    'estimatedDeliveryDate' = undefined;
    /**
    * @member {module:client/models/ItemDeliveryPromise} itemDeliveryPromise
    */
    'itemDeliveryPromise' = undefined;




}
