/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LabelPrepPreference.
* @enum {}
* @readonly
*/
export default class LabelPrepPreference {
        /**
         * value: "SELLER_LABEL"
         * @const
         */
        SELLER_LABEL = "SELLER_LABEL";

        /**
         * value: "AMAZON_LABEL_ONLY"
         * @const
         */
        AMAZON_LABEL_ONLY = "AMAZON_LABEL_ONLY";

        /**
         * value: "AMAZON_LABEL_PREFERRED"
         * @const
         */
        AMAZON_LABEL_PREFERRED = "AMAZON_LABEL_PREFERRED";


    /**
    * Returns a <code>LabelPrepPreference</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:client/models/LabelPrepPreference} The enum <code>LabelPrepPreference</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
