/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LabelDimension from './LabelDimension';
import UnitOfLength from './UnitOfLength';

/**
* The LabelDimensions model module.
* @module client/models/LabelDimensions
* @version v0
*/
export default class LabelDimensions {
    /**
    * Constructs a new <code>LabelDimensions</code>.
    * Dimensions for printing a shipping label.
    * @alias module:client/models/LabelDimensions
    * @class
    * @param length {module:client/models/LabelDimension} 
    * @param width {module:client/models/LabelDimension} 
    * @param unit {module:client/models/UnitOfLength} 
    */

    constructor(length, width, unit) {
        
        
        this['Length'] = length;
        this['Width'] = width;
        this['Unit'] = unit;
        
    }

    /**
    * Constructs a <code>LabelDimensions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/LabelDimensions} obj Optional instance to populate.
    * @return {module:client/models/LabelDimensions} The populated <code>LabelDimensions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LabelDimensions();
                        
            
            if (data.hasOwnProperty('Length')) {
                obj['Length'] = LabelDimension.constructFromObject(data['Length']);
            }
            if (data.hasOwnProperty('Width')) {
                obj['Width'] = LabelDimension.constructFromObject(data['Width']);
            }
            if (data.hasOwnProperty('Unit')) {
                obj['Unit'] = UnitOfLength.constructFromObject(data['Unit']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/LabelDimension} Length
    */
    'Length' = undefined;
    /**
    * @member {module:client/models/LabelDimension} Width
    */
    'Width' = undefined;
    /**
    * @member {module:client/models/UnitOfLength} Unit
    */
    'Unit' = undefined;




}
