/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';

/**
* The LoanServicingEvent model module.
* @module client/models/LoanServicingEvent
* @version v0
*/
export default class LoanServicingEvent {
    /**
    * Constructs a new <code>LoanServicingEvent</code>.
    * A loan advance, loan payment, or loan refund.
    * @alias module:client/models/LoanServicingEvent
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LoanServicingEvent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/LoanServicingEvent} obj Optional instance to populate.
    * @return {module:client/models/LoanServicingEvent} The populated <code>LoanServicingEvent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanServicingEvent();
                        
            
            if (data.hasOwnProperty('LoanAmount')) {
                obj['LoanAmount'] = Currency.constructFromObject(data['LoanAmount']);
            }
            if (data.hasOwnProperty('SourceBusinessEventType')) {
                obj['SourceBusinessEventType'] = ApiClient.convertToType(data['SourceBusinessEventType'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/Currency} LoanAmount
    */
    'LoanAmount' = undefined;
    /**
    * The type of event.  Possible values:  * LoanAdvance  * LoanPayment  * LoanRefund
    * @member {String} SourceBusinessEventType
    */
    'SourceBusinessEventType' = undefined;




}
