/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';
import ModelDate from './ModelDate';

/**
* The NetworkComminglingTransactionEvent model module.
* @module client/models/NetworkComminglingTransactionEvent
* @version v0
*/
export default class NetworkComminglingTransactionEvent {
    /**
    * Constructs a new <code>NetworkComminglingTransactionEvent</code>.
    * A network commingling transaction event.
    * @alias module:client/models/NetworkComminglingTransactionEvent
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NetworkComminglingTransactionEvent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/NetworkComminglingTransactionEvent} obj Optional instance to populate.
    * @return {module:client/models/NetworkComminglingTransactionEvent} The populated <code>NetworkComminglingTransactionEvent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkComminglingTransactionEvent();
                        
            
            if (data.hasOwnProperty('TransactionType')) {
                obj['TransactionType'] = ApiClient.convertToType(data['TransactionType'], 'String');
            }
            if (data.hasOwnProperty('PostedDate')) {
                obj['PostedDate'] = ModelDate.constructFromObject(data['PostedDate']);
            }
            if (data.hasOwnProperty('NetCoTransactionID')) {
                obj['NetCoTransactionID'] = ApiClient.convertToType(data['NetCoTransactionID'], 'String');
            }
            if (data.hasOwnProperty('SwapReason')) {
                obj['SwapReason'] = ApiClient.convertToType(data['SwapReason'], 'String');
            }
            if (data.hasOwnProperty('ASIN')) {
                obj['ASIN'] = ApiClient.convertToType(data['ASIN'], 'String');
            }
            if (data.hasOwnProperty('MarketplaceId')) {
                obj['MarketplaceId'] = ApiClient.convertToType(data['MarketplaceId'], 'String');
            }
            if (data.hasOwnProperty('TaxExclusiveAmount')) {
                obj['TaxExclusiveAmount'] = Currency.constructFromObject(data['TaxExclusiveAmount']);
            }
            if (data.hasOwnProperty('TaxAmount')) {
                obj['TaxAmount'] = Currency.constructFromObject(data['TaxAmount']);
            }
        }
        return obj;
    }

    /**
    * The type of network item swap.  Possible values:  * NetCo - A Fulfillment by Amazon inventory pooling transaction. Available only in the India marketplace.  * ComminglingVAT - A commingling VAT transaction. Available only in the UK, Spain, France, Germany, and Italy marketplaces.
    * @member {String} TransactionType
    */
    'TransactionType' = undefined;
    /**
    * @member {module:client/models/ModelDate} PostedDate
    */
    'PostedDate' = undefined;
    /**
    * The identifier for the network item swap.
    * @member {String} NetCoTransactionID
    */
    'NetCoTransactionID' = undefined;
    /**
    * The reason for the network item swap.
    * @member {String} SwapReason
    */
    'SwapReason' = undefined;
    /**
    * The Amazon Standard Identification Number (ASIN) of the swapped item.
    * @member {String} ASIN
    */
    'ASIN' = undefined;
    /**
    * The marketplace in which the event took place.
    * @member {String} MarketplaceId
    */
    'MarketplaceId' = undefined;
    /**
    * @member {module:client/models/Currency} TaxExclusiveAmount
    */
    'TaxExclusiveAmount' = undefined;
    /**
    * @member {module:client/models/Currency} TaxAmount
    */
    'TaxAmount' = undefined;




}
