/**
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
* The OrderAddress model module.
* @module client/models/OrderAddress
* @version v0
*/
export default class OrderAddress {
    /**
    * Constructs a new <code>OrderAddress</code>.
    * The shipping address for the order.
    * @alias module:client/models/OrderAddress
    * @class
    * @param amazonOrderId {String} An Amazon-defined order identifier, in 3-7-7 format.
    */

    constructor(amazonOrderId) {
        
        
        this['AmazonOrderId'] = amazonOrderId;
        
    }

    /**
    * Constructs a <code>OrderAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/OrderAddress} obj Optional instance to populate.
    * @return {module:client/models/OrderAddress} The populated <code>OrderAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderAddress();
                        
            
            if (data.hasOwnProperty('AmazonOrderId')) {
                obj['AmazonOrderId'] = ApiClient.convertToType(data['AmazonOrderId'], 'String');
            }
            if (data.hasOwnProperty('ShippingAddress')) {
                obj['ShippingAddress'] = Address.constructFromObject(data['ShippingAddress']);
            }
        }
        return obj;
    }

    /**
    * An Amazon-defined order identifier, in 3-7-7 format.
    * @member {String} AmazonOrderId
    */
    'AmazonOrderId' = undefined;
    /**
    * @member {module:client/models/Address} ShippingAddress
    */
    'ShippingAddress' = undefined;




}
