/**
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BuyerCustomizedInfoDetail from './BuyerCustomizedInfoDetail';
import Money from './Money';

/**
* The OrderItemBuyerInfo model module.
* @module client/models/OrderItemBuyerInfo
* @version v0
*/
export default class OrderItemBuyerInfo {
    /**
    * Constructs a new <code>OrderItemBuyerInfo</code>.
    * A single order item&#x27;s buyer information.
    * @alias module:client/models/OrderItemBuyerInfo
    * @class
    * @param orderItemId {String} An Amazon-defined order item identifier.
    */

    constructor(orderItemId) {
        
        
        this['OrderItemId'] = orderItemId;
        
    }

    /**
    * Constructs a <code>OrderItemBuyerInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/OrderItemBuyerInfo} obj Optional instance to populate.
    * @return {module:client/models/OrderItemBuyerInfo} The populated <code>OrderItemBuyerInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderItemBuyerInfo();
                        
            
            if (data.hasOwnProperty('OrderItemId')) {
                obj['OrderItemId'] = ApiClient.convertToType(data['OrderItemId'], 'String');
            }
            if (data.hasOwnProperty('BuyerCustomizedInfo')) {
                obj['BuyerCustomizedInfo'] = BuyerCustomizedInfoDetail.constructFromObject(data['BuyerCustomizedInfo']);
            }
            if (data.hasOwnProperty('GiftWrapPrice')) {
                obj['GiftWrapPrice'] = Money.constructFromObject(data['GiftWrapPrice']);
            }
            if (data.hasOwnProperty('GiftWrapTax')) {
                obj['GiftWrapTax'] = Money.constructFromObject(data['GiftWrapTax']);
            }
            if (data.hasOwnProperty('GiftMessageText')) {
                obj['GiftMessageText'] = ApiClient.convertToType(data['GiftMessageText'], 'String');
            }
            if (data.hasOwnProperty('GiftWrapLevel')) {
                obj['GiftWrapLevel'] = ApiClient.convertToType(data['GiftWrapLevel'], 'String');
            }
        }
        return obj;
    }

    /**
    * An Amazon-defined order item identifier.
    * @member {String} OrderItemId
    */
    'OrderItemId' = undefined;
    /**
    * @member {module:client/models/BuyerCustomizedInfoDetail} BuyerCustomizedInfo
    */
    'BuyerCustomizedInfo' = undefined;
    /**
    * @member {module:client/models/Money} GiftWrapPrice
    */
    'GiftWrapPrice' = undefined;
    /**
    * @member {module:client/models/Money} GiftWrapTax
    */
    'GiftWrapTax' = undefined;
    /**
    * A gift message provided by the buyer.
    * @member {String} GiftMessageText
    */
    'GiftMessageText' = undefined;
    /**
    * The gift wrap level specified by the buyer.
    * @member {String} GiftWrapLevel
    */
    'GiftWrapLevel' = undefined;




}
