/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';
import Contact from './Contact';
import DateStringType from './DateStringType';
import PalletList from './PalletList';
import SellerFreightClass from './SellerFreightClass';
import UnsignedIntType from './UnsignedIntType';
import Weight from './Weight';

/**
* The PartneredLtlDataInput model module.
* @module client/models/PartneredLtlDataInput
* @version v0
*/
export default class PartneredLtlDataInput {
    /**
    * Constructs a new <code>PartneredLtlDataInput</code>.
    * Information that is required by an Amazon-partnered carrier to ship a Less Than Truckload/Full Truckload (LTL/FTL) inbound shipment.
    * @alias module:client/models/PartneredLtlDataInput
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PartneredLtlDataInput</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/PartneredLtlDataInput} obj Optional instance to populate.
    * @return {module:client/models/PartneredLtlDataInput} The populated <code>PartneredLtlDataInput</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartneredLtlDataInput();
                        
            
            if (data.hasOwnProperty('Contact')) {
                obj['Contact'] = Contact.constructFromObject(data['Contact']);
            }
            if (data.hasOwnProperty('BoxCount')) {
                obj['BoxCount'] = UnsignedIntType.constructFromObject(data['BoxCount']);
            }
            if (data.hasOwnProperty('SellerFreightClass')) {
                obj['SellerFreightClass'] = SellerFreightClass.constructFromObject(data['SellerFreightClass']);
            }
            if (data.hasOwnProperty('FreightReadyDate')) {
                obj['FreightReadyDate'] = DateStringType.constructFromObject(data['FreightReadyDate']);
            }
            if (data.hasOwnProperty('PalletList')) {
                obj['PalletList'] = PalletList.constructFromObject(data['PalletList']);
            }
            if (data.hasOwnProperty('TotalWeight')) {
                obj['TotalWeight'] = Weight.constructFromObject(data['TotalWeight']);
            }
            if (data.hasOwnProperty('SellerDeclaredValue')) {
                obj['SellerDeclaredValue'] = Amount.constructFromObject(data['SellerDeclaredValue']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/Contact} Contact
    */
    'Contact' = undefined;
    /**
    * @member {module:client/models/UnsignedIntType} BoxCount
    */
    'BoxCount' = undefined;
    /**
    * @member {module:client/models/SellerFreightClass} SellerFreightClass
    */
    'SellerFreightClass' = undefined;
    /**
    * @member {module:client/models/DateStringType} FreightReadyDate
    */
    'FreightReadyDate' = undefined;
    /**
    * @member {module:client/models/PalletList} PalletList
    */
    'PalletList' = undefined;
    /**
    * @member {module:client/models/Weight} TotalWeight
    */
    'TotalWeight' = undefined;
    /**
    * @member {module:client/models/Amount} SellerDeclaredValue
    */
    'SellerDeclaredValue' = undefined;




}
