/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PartneredEstimate from './PartneredEstimate';
import PartneredSmallParcelPackageOutputList from './PartneredSmallParcelPackageOutputList';

/**
* The PartneredSmallParcelDataOutput model module.
* @module client/models/PartneredSmallParcelDataOutput
* @version v0
*/
export default class PartneredSmallParcelDataOutput {
    /**
    * Constructs a new <code>PartneredSmallParcelDataOutput</code>.
    * Information returned by Amazon about a Small Parcel shipment by an Amazon-partnered carrier.
    * @alias module:client/models/PartneredSmallParcelDataOutput
    * @class
    * @param packageList {module:client/models/PartneredSmallParcelPackageOutputList} 
    */

    constructor(packageList) {
        
        
        this['PackageList'] = packageList;
        
    }

    /**
    * Constructs a <code>PartneredSmallParcelDataOutput</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/PartneredSmallParcelDataOutput} obj Optional instance to populate.
    * @return {module:client/models/PartneredSmallParcelDataOutput} The populated <code>PartneredSmallParcelDataOutput</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartneredSmallParcelDataOutput();
                        
            
            if (data.hasOwnProperty('PackageList')) {
                obj['PackageList'] = PartneredSmallParcelPackageOutputList.constructFromObject(data['PackageList']);
            }
            if (data.hasOwnProperty('PartneredEstimate')) {
                obj['PartneredEstimate'] = PartneredEstimate.constructFromObject(data['PartneredEstimate']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/PartneredSmallParcelPackageOutputList} PackageList
    */
    'PackageList' = undefined;
    /**
    * @member {module:client/models/PartneredEstimate} PartneredEstimate
    */
    'PartneredEstimate' = undefined;




}
