/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PartneredSmallParcelPackageOutput from './PartneredSmallParcelPackageOutput';

/**
* The PartneredSmallParcelPackageOutputList model module.
* @module client/models/PartneredSmallParcelPackageOutputList
* @version v0
*/
export default class PartneredSmallParcelPackageOutputList extends Array {
    /**
    * Constructs a new <code>PartneredSmallParcelPackageOutputList</code>.
    * A list of packages, including shipping information from the Amazon-partnered carrier.
    * @alias module:client/models/PartneredSmallParcelPackageOutputList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>PartneredSmallParcelPackageOutputList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/PartneredSmallParcelPackageOutputList} obj Optional instance to populate.
    * @return {module:client/models/PartneredSmallParcelPackageOutputList} The populated <code>PartneredSmallParcelPackageOutputList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartneredSmallParcelPackageOutputList();
            ApiClient.constructFromObject(data, obj, 'PartneredSmallParcelPackageOutput');
            
            
        }
        return obj;
    }





}
