/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MoneyType from './MoneyType';

/**
* The Points model module.
* @module client/models/Points
* @version v0
*/
export default class Points {
    /**
    * Constructs a new <code>Points</code>.
    * @alias module:client/models/Points
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Points</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/Points} obj Optional instance to populate.
    * @return {module:client/models/Points} The populated <code>Points</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Points();
                        
            
            if (data.hasOwnProperty('PointsNumber')) {
                obj['PointsNumber'] = ApiClient.convertToType(data['PointsNumber'], 'Number');
            }
            if (data.hasOwnProperty('PointsMonetaryValue')) {
                obj['PointsMonetaryValue'] = MoneyType.constructFromObject(data['PointsMonetaryValue']);
            }
        }
        return obj;
    }

    /**
    * The number of points.
    * @member {Number} PointsNumber
    */
    'PointsNumber' = undefined;
    /**
    * @member {module:client/models/MoneyType} PointsMonetaryValue
    */
    'PointsMonetaryValue' = undefined;




}
