/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PrepInstruction.
* @enum {}
* @readonly
*/
export default class PrepInstruction {
        /**
         * value: "Polybagging"
         * @const
         */
        Polybagging = "Polybagging";

        /**
         * value: "BubbleWrapping"
         * @const
         */
        BubbleWrapping = "BubbleWrapping";

        /**
         * value: "Taping"
         * @const
         */
        Taping = "Taping";

        /**
         * value: "BlackShrinkWrapping"
         * @const
         */
        BlackShrinkWrapping = "BlackShrinkWrapping";

        /**
         * value: "Labeling"
         * @const
         */
        Labeling = "Labeling";

        /**
         * value: "HangGarment"
         * @const
         */
        HangGarment = "HangGarment";


    /**
    * Returns a <code>PrepInstruction</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:client/models/PrepInstruction} The enum <code>PrepInstruction</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
