/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LabelResultList from './LabelResultList';
import ServiceRate from './ServiceRate';
import ShipmentId from './ShipmentId';

/**
* The PurchaseShipmentResult model module.
* @module client/models/PurchaseShipmentResult
* @version v1
*/
export default class PurchaseShipmentResult {
    /**
    * Constructs a new <code>PurchaseShipmentResult</code>.
    * The payload schema for the purchaseShipment operation.
    * @alias module:client/models/PurchaseShipmentResult
    * @class
    * @param shipmentId {module:client/models/ShipmentId} 
    * @param serviceRate {module:client/models/ServiceRate} 
    * @param labelResults {module:client/models/LabelResultList} 
    */

    constructor(shipmentId, serviceRate, labelResults) {
        
        
        this['shipmentId'] = shipmentId;
        this['serviceRate'] = serviceRate;
        this['labelResults'] = labelResults;
        
    }

    /**
    * Constructs a <code>PurchaseShipmentResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/PurchaseShipmentResult} obj Optional instance to populate.
    * @return {module:client/models/PurchaseShipmentResult} The populated <code>PurchaseShipmentResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseShipmentResult();
                        
            
            if (data.hasOwnProperty('shipmentId')) {
                obj['shipmentId'] = ShipmentId.constructFromObject(data['shipmentId']);
            }
            if (data.hasOwnProperty('serviceRate')) {
                obj['serviceRate'] = ServiceRate.constructFromObject(data['serviceRate']);
            }
            if (data.hasOwnProperty('labelResults')) {
                obj['labelResults'] = LabelResultList.constructFromObject(data['labelResults']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/ShipmentId} shipmentId
    */
    'shipmentId' = undefined;
    /**
    * @member {module:client/models/ServiceRate} serviceRate
    */
    'serviceRate' = undefined;
    /**
    * @member {module:client/models/LabelResultList} labelResults
    */
    'labelResults' = undefined;




}
