/**
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2020-09-04
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Report from './Report';

/**
* The ReportList model module.
* @module client/models/ReportList
* @version 2020-09-04
*/
export default class ReportList extends Array {
    /**
    * Constructs a new <code>ReportList</code>.
    * @alias module:client/models/ReportList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>ReportList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ReportList} obj Optional instance to populate.
    * @return {module:client/models/ReportList} The populated <code>ReportList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportList();
            ApiClient.constructFromObject(data, obj, 'Report');
            
            
        }
        return obj;
    }





}
