/**
 * Selling Partner API for FBA Small And Light
 * The Selling Partner API for FBA Small and Light lets you help sellers manage their listings in the Small and Light program. The program reduces the cost of fulfilling orders for small and lightweight FBA inventory. You can enroll or remove items from the program and check item eligibility and enrollment status. You can also preview the estimated program fees charged to a seller for items sold while enrolled in the program.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SellerSKU model module.
* @module client/models/SellerSKU
* @version v1
*/
export default class SellerSKU {
    /**
    * Constructs a new <code>SellerSKU</code>.
    * Identifies an item in the given marketplace. SellerSKU is qualified by the seller&#x27;s SellerId, which is included with every operation that you submit.
    * @alias module:client/models/SellerSKU
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SellerSKU</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/SellerSKU} obj Optional instance to populate.
    * @return {module:client/models/SellerSKU} The populated <code>SellerSKU</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellerSKU();
                        
            
        }
        return obj;
    }





}
