/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';
import ServiceType from './ServiceType';
import ShippingPromiseSet from './ShippingPromiseSet';
import Weight from './Weight';

/**
* The ServiceRate model module.
* @module client/models/ServiceRate
* @version v1
*/
export default class ServiceRate {
    /**
    * Constructs a new <code>ServiceRate</code>.
    * The specific rate for a shipping service, or null if no service available.
    * @alias module:client/models/ServiceRate
    * @class
    * @param totalCharge {module:client/models/Currency} 
    * @param billableWeight {module:client/models/Weight} 
    * @param serviceType {module:client/models/ServiceType} 
    * @param promise {module:client/models/ShippingPromiseSet} 
    */

    constructor(totalCharge, billableWeight, serviceType, promise) {
        
        
        this['totalCharge'] = totalCharge;
        this['billableWeight'] = billableWeight;
        this['serviceType'] = serviceType;
        this['promise'] = promise;
        
    }

    /**
    * Constructs a <code>ServiceRate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ServiceRate} obj Optional instance to populate.
    * @return {module:client/models/ServiceRate} The populated <code>ServiceRate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceRate();
                        
            
            if (data.hasOwnProperty('totalCharge')) {
                obj['totalCharge'] = Currency.constructFromObject(data['totalCharge']);
            }
            if (data.hasOwnProperty('billableWeight')) {
                obj['billableWeight'] = Weight.constructFromObject(data['billableWeight']);
            }
            if (data.hasOwnProperty('serviceType')) {
                obj['serviceType'] = ServiceType.constructFromObject(data['serviceType']);
            }
            if (data.hasOwnProperty('promise')) {
                obj['promise'] = ShippingPromiseSet.constructFromObject(data['promise']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/Currency} totalCharge
    */
    'totalCharge' = undefined;
    /**
    * @member {module:client/models/Weight} billableWeight
    */
    'billableWeight' = undefined;
    /**
    * @member {module:client/models/ServiceType} serviceType
    */
    'serviceType' = undefined;
    /**
    * @member {module:client/models/ShippingPromiseSet} promise
    */
    'promise' = undefined;




}
