/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CarrierWillPickUpOption from './CarrierWillPickUpOption';
import CurrencyAmount from './CurrencyAmount';
import DeliveryExperienceType from './DeliveryExperienceType';
import LabelFormat from './LabelFormat';

/**
* The ShippingServiceOptions model module.
* @module client/models/ShippingServiceOptions
* @version v0
*/
export default class ShippingServiceOptions {
    /**
    * Constructs a new <code>ShippingServiceOptions</code>.
    * Extra services provided by a carrier.
    * @alias module:client/models/ShippingServiceOptions
    * @class
    * @param deliveryExperience {module:client/models/DeliveryExperienceType} 
    * @param carrierWillPickUp {Boolean} When true, the carrier will pick up the package.  Note: Scheduled carrier pickup is available only using Dynamex (US), DPD (UK), and Royal Mail (UK).
    */

    constructor(deliveryExperience, carrierWillPickUp) {
        
        
        this['DeliveryExperience'] = deliveryExperience;
        this['CarrierWillPickUp'] = carrierWillPickUp;
        
    }

    /**
    * Constructs a <code>ShippingServiceOptions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ShippingServiceOptions} obj Optional instance to populate.
    * @return {module:client/models/ShippingServiceOptions} The populated <code>ShippingServiceOptions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShippingServiceOptions();
                        
            
            if (data.hasOwnProperty('DeliveryExperience')) {
                obj['DeliveryExperience'] = DeliveryExperienceType.constructFromObject(data['DeliveryExperience']);
            }
            if (data.hasOwnProperty('DeclaredValue')) {
                obj['DeclaredValue'] = CurrencyAmount.constructFromObject(data['DeclaredValue']);
            }
            if (data.hasOwnProperty('CarrierWillPickUp')) {
                obj['CarrierWillPickUp'] = ApiClient.convertToType(data['CarrierWillPickUp'], 'Boolean');
            }
            if (data.hasOwnProperty('CarrierWillPickUpOption')) {
                obj['CarrierWillPickUpOption'] = CarrierWillPickUpOption.constructFromObject(data['CarrierWillPickUpOption']);
            }
            if (data.hasOwnProperty('LabelFormat')) {
                obj['LabelFormat'] = LabelFormat.constructFromObject(data['LabelFormat']);
            }
        }
        return obj;
    }

    /**
    * @member {module:client/models/DeliveryExperienceType} DeliveryExperience
    */
    'DeliveryExperience' = undefined;
    /**
    * @member {module:client/models/CurrencyAmount} DeclaredValue
    */
    'DeclaredValue' = undefined;
    /**
    * When true, the carrier will pick up the package.  Note: Scheduled carrier pickup is available only using Dynamex (US), DPD (UK), and Royal Mail (UK).
    * @member {Boolean} CarrierWillPickUp
    */
    'CarrierWillPickUp' = undefined;
    /**
    * @member {module:client/models/CarrierWillPickUpOption} CarrierWillPickUpOption
    */
    'CarrierWillPickUpOption' = undefined;
    /**
    * @member {module:client/models/LabelFormat} LabelFormat
    */
    'LabelFormat' = undefined;




}
