/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChargeComponentList from './ChargeComponentList';
import Currency from './Currency';
import FeeComponentList from './FeeComponentList';
import PromotionList from './PromotionList';
import TaxWithheldComponentList from './TaxWithheldComponentList';

/**
* The ShipmentItem model module.
* @module client/models/ShipmentItem
* @version v0
*/
export default class ShipmentItem {
    /**
    * Constructs a new <code>ShipmentItem</code>.
    * An item of a shipment, refund, guarantee claim, or chargeback.
    * @alias module:client/models/ShipmentItem
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ShipmentItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/ShipmentItem} obj Optional instance to populate.
    * @return {module:client/models/ShipmentItem} The populated <code>ShipmentItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShipmentItem();
                        
            
            if (data.hasOwnProperty('SellerSKU')) {
                obj['SellerSKU'] = ApiClient.convertToType(data['SellerSKU'], 'String');
            }
            if (data.hasOwnProperty('OrderItemId')) {
                obj['OrderItemId'] = ApiClient.convertToType(data['OrderItemId'], 'String');
            }
            if (data.hasOwnProperty('OrderAdjustmentItemId')) {
                obj['OrderAdjustmentItemId'] = ApiClient.convertToType(data['OrderAdjustmentItemId'], 'String');
            }
            if (data.hasOwnProperty('QuantityShipped')) {
                obj['QuantityShipped'] = ApiClient.convertToType(data['QuantityShipped'], 'Number');
            }
            if (data.hasOwnProperty('ItemChargeList')) {
                obj['ItemChargeList'] = ChargeComponentList.constructFromObject(data['ItemChargeList']);
            }
            if (data.hasOwnProperty('ItemChargeAdjustmentList')) {
                obj['ItemChargeAdjustmentList'] = ChargeComponentList.constructFromObject(data['ItemChargeAdjustmentList']);
            }
            if (data.hasOwnProperty('ItemFeeList')) {
                obj['ItemFeeList'] = FeeComponentList.constructFromObject(data['ItemFeeList']);
            }
            if (data.hasOwnProperty('ItemFeeAdjustmentList')) {
                obj['ItemFeeAdjustmentList'] = FeeComponentList.constructFromObject(data['ItemFeeAdjustmentList']);
            }
            if (data.hasOwnProperty('ItemTaxWithheldList')) {
                obj['ItemTaxWithheldList'] = TaxWithheldComponentList.constructFromObject(data['ItemTaxWithheldList']);
            }
            if (data.hasOwnProperty('PromotionList')) {
                obj['PromotionList'] = PromotionList.constructFromObject(data['PromotionList']);
            }
            if (data.hasOwnProperty('PromotionAdjustmentList')) {
                obj['PromotionAdjustmentList'] = PromotionList.constructFromObject(data['PromotionAdjustmentList']);
            }
            if (data.hasOwnProperty('CostOfPointsGranted')) {
                obj['CostOfPointsGranted'] = Currency.constructFromObject(data['CostOfPointsGranted']);
            }
            if (data.hasOwnProperty('CostOfPointsReturned')) {
                obj['CostOfPointsReturned'] = Currency.constructFromObject(data['CostOfPointsReturned']);
            }
        }
        return obj;
    }

    /**
    * The seller SKU of the item. The seller SKU is qualified by the seller's seller ID, which is included with every call to the Selling Partner API.
    * @member {String} SellerSKU
    */
    'SellerSKU' = undefined;
    /**
    * An Amazon-defined order item identifier.
    * @member {String} OrderItemId
    */
    'OrderItemId' = undefined;
    /**
    * An Amazon-defined order adjustment identifier defined for refunds, guarantee claims, and chargeback events.
    * @member {String} OrderAdjustmentItemId
    */
    'OrderAdjustmentItemId' = undefined;
    /**
    * The number of items shipped.
    * @member {Number} QuantityShipped
    */
    'QuantityShipped' = undefined;
    /**
    * @member {module:client/models/ChargeComponentList} ItemChargeList
    */
    'ItemChargeList' = undefined;
    /**
    * @member {module:client/models/ChargeComponentList} ItemChargeAdjustmentList
    */
    'ItemChargeAdjustmentList' = undefined;
    /**
    * @member {module:client/models/FeeComponentList} ItemFeeList
    */
    'ItemFeeList' = undefined;
    /**
    * @member {module:client/models/FeeComponentList} ItemFeeAdjustmentList
    */
    'ItemFeeAdjustmentList' = undefined;
    /**
    * @member {module:client/models/TaxWithheldComponentList} ItemTaxWithheldList
    */
    'ItemTaxWithheldList' = undefined;
    /**
    * @member {module:client/models/PromotionList} PromotionList
    */
    'PromotionList' = undefined;
    /**
    * @member {module:client/models/PromotionList} PromotionAdjustmentList
    */
    'PromotionAdjustmentList' = undefined;
    /**
    * @member {module:client/models/Currency} CostOfPointsGranted
    */
    'CostOfPointsGranted' = undefined;
    /**
    * @member {module:client/models/Currency} CostOfPointsReturned
    */
    'CostOfPointsReturned' = undefined;




}
