/**
 * Selling Partner API for FBA Small And Light
 * The Selling Partner API for FBA Small and Light lets you help sellers manage their listings in the Small and Light program. The program reduces the cost of fulfilling orders for small and lightweight FBA inventory. You can enroll or remove items from the program and check item eligibility and enrollment status. You can also preview the estimated program fees charged to a seller for items sold while enrolled in the program.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FeePreview from './FeePreview';

/**
* The SmallAndLightFeePreviews model module.
* @module client/models/SmallAndLightFeePreviews
* @version v1
*/
export default class SmallAndLightFeePreviews {
    /**
    * Constructs a new <code>SmallAndLightFeePreviews</code>.
    * @alias module:client/models/SmallAndLightFeePreviews
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SmallAndLightFeePreviews</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/SmallAndLightFeePreviews} obj Optional instance to populate.
    * @return {module:client/models/SmallAndLightFeePreviews} The populated <code>SmallAndLightFeePreviews</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmallAndLightFeePreviews();
                        
            
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [FeePreview]);
            }
        }
        return obj;
    }

    /**
    * A list of fee estimates for the requested items. The order of the fee estimates will follow the same order as the items in the request, with duplicates removed.
    * @member {Array.<module:client/models/FeePreview>} data
    */
    'data' = undefined;




}
