/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TermsAndConditionsNotAcceptedCarrier from './TermsAndConditionsNotAcceptedCarrier';

/**
* The TermsAndConditionsNotAcceptedCarrierList model module.
* @module client/models/TermsAndConditionsNotAcceptedCarrierList
* @version v0
*/
export default class TermsAndConditionsNotAcceptedCarrierList extends Array {
    /**
    * Constructs a new <code>TermsAndConditionsNotAcceptedCarrierList</code>.
    * List of carriers whose terms and conditions were not accepted by the seller.
    * @alias module:client/models/TermsAndConditionsNotAcceptedCarrierList
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>TermsAndConditionsNotAcceptedCarrierList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/TermsAndConditionsNotAcceptedCarrierList} obj Optional instance to populate.
    * @return {module:client/models/TermsAndConditionsNotAcceptedCarrierList} The populated <code>TermsAndConditionsNotAcceptedCarrierList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TermsAndConditionsNotAcceptedCarrierList();
            ApiClient.constructFromObject(data, obj, 'TermsAndConditionsNotAcceptedCarrier');
            
            
        }
        return obj;
    }





}
