/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TimeRange model module.
* @module client/models/TimeRange
* @version v1
*/
export default class TimeRange {
    /**
    * Constructs a new <code>TimeRange</code>.
    * The time range.
    * @alias module:client/models/TimeRange
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TimeRange</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/TimeRange} obj Optional instance to populate.
    * @return {module:client/models/TimeRange} The populated <code>TimeRange</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeRange();
                        
            
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Date');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The start date and time. This defaults to the current date and time.
    * @member {Date} start
    */
    'start' = undefined;
    /**
    * The end date and time. This must come after the value of start. This defaults to the next business day from the start.
    * @member {Date} end
    */
    'end' = undefined;




}
