/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Weight model module.
* @module client/models/Weight
* @version v1
*/
export default class Weight {
    /**
    * Constructs a new <code>Weight</code>.
    * The weight.
    * @alias module:client/models/Weight
    * @class
    * @param unit {module:client/models/Weight.UnitEnum} The unit of measurement.
    * @param value {Number} The measurement value.
    */

    constructor(unit, value) {
        
        
        this['unit'] = unit;
        this['value'] = value;
        
    }

    /**
    * Constructs a <code>Weight</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/models/Weight} obj Optional instance to populate.
    * @return {module:client/models/Weight} The populated <code>Weight</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Weight();
                        
            
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The unit of measurement.
    * @member {module:client/models/Weight.UnitEnum} unit
    */
    'unit' = undefined;
    /**
    * The measurement value.
    * @member {Number} value
    */
    'value' = undefined;



    /**
    * Allowed values for the <code>unit</code> property.
    * @enum {String}
    * @readonly
    */
    static UnitEnum = {
        /**
         * value: "g"
         * @const
         */
        "g": "g",
        /**
         * value: "kg"
         * @const
         */
        "kg": "kg",
        /**
         * value: "oz"
         * @const
         */
        "oz": "oz",
        /**
         * value: "lb"
         * @const
         */
        "lb": "lb"    };

}
